# Generated by Django 4.2.7 on 2023-11-28 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderlines_order_alter_orders_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlines',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orders'),
        ),
    ]
