# Generated by Django 4.2.7 on 2023-11-28 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='product title')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='assets/products/', verbose_name='image of product')),
                ('summary', models.TextField(max_length=200, verbose_name='product summary')),
                ('description', models.TextField(max_length=200, verbose_name='product description')),
                ('price', models.FloatField(default=0.0, verbose_name='product price (GH)')),
                ('discount_type', models.CharField(choices=[('none', 'None'), ('percent', 'Percent'), ('amount', 'Amount'), ('currency', 'Currency')], default='none', max_length=10, verbose_name='discount type')),
                ('discount_value', models.FloatField(default=0.0, verbose_name='discount value')),
                ('tags', models.CharField(max_length=100, verbose_name='tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('poor', 'Poor'), ('unsatisfactory', 'Unsatisfactory'), ('satisfactory', 'Satisfactory'), ('very satisfactory', 'Very Satisfactory'), ('outstanding', 'Outstanding')], max_length=30)),
                ('comments', models.TextField(blank=True, max_length=255, verbose_name='comments')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.products', to_field='title', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('-created_at',),
            },
        ),
    ]
