# Generated by Django 4.2.7 on 2023-11-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_categories_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(null=True, upload_to='assets/products/', verbose_name='image of product'),
        ),
    ]
