# Generated by Django 4.2.7 on 2023-11-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='assets/products/', verbose_name='image of product'),
        ),
    ]
