# Generated by Django 4.2.7 on 2023-11-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_products_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
