# Generated by Django 4.2.7 on 2023-11-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
        ('cart', '0005_alter_carts_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart_id', 'product_id')},
        ),
    ]
