# Generated by Django 4.2.7 on 2023-11-20 10:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('slug', models.SlugField(blank=True, max_length=100, verbose_name='A short label for URLs')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('customer', 'Customer')], max_length=10)),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='unique user name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name="person's first name")),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name="person's last name")),
                ('avatar', models.ImageField(blank=True, upload_to='', verbose_name='profile picture')),
                ('locale', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ru', 'Russian'), ('ko', 'Korean'), ('zh', 'Chinese'), ('ha', 'Hauza')], verbose_name='locale setting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('email_validated', models.BooleanField(default=False)),
                ('phone_validated', models.BooleanField(default=False)),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Custome User',
                'verbose_name_plural': 'Custome Users',
                'ordering': ('-created_at',),
            },
        ),
    ]
