# Generated by Django 4.2.7 on 2023-11-22 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('-date_joined',), 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='created_at',
            new_name='date_joined',
        ),
    ]
