# Generated by Django 4.2.7 on 2023-11-20 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_credentials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
