# Generated by Django 4.2.7 on 2023-11-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_user_id_credentials_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='../assets/customers/', verbose_name='profile picture'),
        ),
    ]
